spring.application.name=ai-codelab-backend

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ai_coding_platform

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

jwt.secret=${JWT_SECRET}

server.port=8080